import Head from 'next/head';
import Link from 'next/link';
// import Login from '../components/login/login';
import styles from '../styles/globals.css'
// import Home from './index';
// import login from './login';




export default function Home() {
  return (

    <nav>
      <ul className="menu-bar">
        <li>
        <Link href='/'>
          <a >Home</a>
        </Link>
        </li>
        <li>
        <Link href='/register'>
          <a >egister</a>
        </Link>
        </li>
        <li>
        <Link href='/login'>
          <a >Login</a>
        </Link>
        </li>
       <li>
       <Link href='/contact'>
          <a >Contact Us</a>
        </Link>
       </li>
        
      </ul>
    </nav>,

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <home />
      </div>
    </div>
  )
}